### ISSUE TITLE
Premailer or getopt gems not installed

### ISSUE THREAD

**Issue by pabloleone** [emilsundberg/Laravel-HTML-email-inliner#11]
I tried to install the dependencies you mentioned in here https://gist.github.com/emilsundberg/8ae10ca886058c683d13 but it didn't work.

The first mention is that Premailer requires ruby >= 2.0.0.

ERROR:  Error installing premailer:
    premailer requires Ruby version >= 2.0.0.

Even installing ruby 2.0.0, I still getting that error message.

I tried also latest ruby version, but nothing seems to work. I'm using homestead version 0.4.4.

Thank you.

**Comment by emilsundberg** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5izYFiwJ&#x2F;2-test3"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> test3</a>

**Comment by emilsundberg** [comment]
What happens if you install the latest version of nokogiri, premailer and getopt?
