### ISSUE TITLE
Not working, Laravel 4.2 and Mailgun driver

### ISSUE THREAD

**Issue by opheliadesign** [emilsundberg/Laravel-HTML-email-inliner#5]
I am attempting to use this with Laravel 4.2 and the Mailgun driver. I have installed the required system dependancies in Homestead as per the linked Gist, installed the package via Composer, and added the Provider in the config.

When I send emails they are not being inlined. Do I need to do something prior to sending the email in order to enable this? Also, when I attempt to call Inliner::isEnabled() I receive the following exception: Non-static method Emil\Inliner\Inliner::isEnabled() should not be called statically

**Comment by emilsundberg** [comment]
You should not have to enable anything. Have you added both the service provider and the alias in your app.php?

It sounds like you have a use statement for the `Emil\Inliner\Inliner` class which is not necessary. Inliner::enable() should be called trough the facade. 

I'll need some code to know what's going on. It should work with all providers. If you set the provider to log you should see an inlined html email in your laravel.log
