### ISSUE TITLE
Broken in Laravel 5.0

### ISSUE THREAD

**Issue by DavidLemayian** [emilsundberg/Laravel-HTML-email-inliner#6]
[This line of code](https://github.com/emilsundberg/Laravel-HTML-email-inliner/blob/master/src/Emil/Inliner/InlinerServiceProvider.php#L21) breaks the app on Laravel 5.0.

```
BadMethodCallException in ServiceProvider.php line 226:
Call to undefined method [package]
```

I would love to suggest a fix but don't know enough in package development.

**Comment by emilsundberg** [comment]
This package is now compatible with Laravel 5.1 (currently on `dev-master`)

**Comment by DavidLemayian** [comment]
@emilsundberg :+1:
