### ISSUE TITLE
Premailer or getopt gems not installed

### ISSUE THREAD

**Issue by kadirarlii** [emilsundberg/Laravel-HTML-email-inliner#8]
Inliner::isEnabled() is true but error Exception.

"Premailer or getopt gems not installed"

 $scriptPath = dirname(__FILE__) . '/converter.rb';
            $output = array();
            $returnVar = 0;
            $command = ($scriptPath) . ' ' . $this->_getArgumentString();
            $response = exec($command, $output, $returnVar);
            unlink($this->cacheDir . $this->fileName);
            if ($returnVar === 1) {
                throw new Exception('Premailer or getopt gems not installed');
            }
            return implode('', $output);

I install these.
$ sudo gem install premailer
$ sudo gem install getopt
and
"require": {
    "emil/inliner": "dev-master"
}
"providers" => [
    'Emil\Inliner\InlinerServiceProvider',
]

composer update

I use localhost on mac.

Can you help me?

**Comment by kadirarlii** [comment]
I install
sudo gem install nokogiri
Fixed my problem :)
Thank you.

**Comment by emilsundberg** [comment]
Great :) The error message is a bit vague when you are missing the required gems.
