### ISSUE TITLE
Case sensitivity problem vendor folder

### ISSUE THREAD

**Issue by meertensm** [emilsundberg/Laravel-HTML-email-inliner#9]
Hi Emil,

In Inliner.php on line 5 you reference the vendor folder as 'Vendor' while the folder itself is written as 'vendor'. 

On my mac everything works fine but on ubuntu php throws a fatal error:
Class 'Emil\Inliner\Vendor\Premailer\Premailer not found.

**Comment by emilsundberg** [comment]
Is this really a problem? Line 5 on `Inliner.php` defines the namespace. It does work fine for me on my ubuntu box.

If you change what you believe is wrong, does that solve the issue you have?

**Comment by Jaspur** [comment]
Same here: 
```
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Emil\Inliner\Vendor\Premailer\Premailer' not found
```
But mail is send..
